export const siteConfig = {
  name: "Shihab Haque - Full-Stack Web & App Developer",
  authorName: "ShihabHaque",
  username: "shihabhq",
  description:
    "Shihab Haque - Full-Stack Web & App Developer working at the intersection of AI, data, and scalable software systems. Explore my projects, experience, and contributions in software development and AI.",
  url: "https://shihab.live",
  links: {
    twitter: "https://x.com/shihab_hq",
    github: "https://github.com/shihabhq",
    linkedin: "https://linkedin.com/in/shihabhq",
    x: "https://x.com/shihab_hq",
    email: "shihabhq@yahoo.com",
  },
  ogImage: "https://ik.imagekit.io/bua2b1x6j/portfolio/og.webp",
  iconIco: "https://ik.imagekit.io/bua2b1x6j/portfolio/logo.webp",
  logoIcon: "https://ik.imagekit.io/bua2b1x6j/portfolio/logo.webp",
  keywords: [
    "Shihab Haque",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Typescript  Developer",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
  ],
};
